main: com.cerrealic.naturalcobwebs.NaturalCobwebsPlugin
name: NaturalCobwebs
version: a0.1.0
api-version: 1.16
description: Plugin that fills nooks and crannies with cobwebs over time.
author: cerrealic
